apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yajn27hak-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yajn27hak-go 
  name: yajn27hak-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yajn27hak-go 
